version: "3.9"

services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  user-service:
    image: user-service:latest
    container_name: user-service
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"
    networks:
      - app-network

  task-service:
    image: task-service:latest
    container_name: task-service
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - app-network

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    depends_on:
      - eureka-server
    ports:
      - "8083:8083"
    networks:
      - app-network

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    depends_on:
      - eureka-server
      - user-service
      - task-service
      - notification-service
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
