version: '3.8'
services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    networks:
      - app-network

  task-service:
    image: task-service:latest
    container_name: task-service
    build:
      context: ./task-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    networks:
      - app-network

  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
